name: Windows Smoke Build

on:
  workflow_dispatch:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    strategy:
      matrix:
        platform: [x86, x64]
        config: [Debug, Release]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: 'f7423ee180c4b7f40d43402c2feb3859161ef625'
          vcpkgJsonGlob: 'vcpkg.json'
          runVcpkgInstall: true

      - name: Run smoke build (with vcpkg)
        shell: pwsh
        run: |
          Write-Host "=== Windows Smoke Build ==="
          Write-Host "Platform: ${{ matrix.platform }}"
          Write-Host "Config: ${{ matrix.config }}"
          
          # Use the build script with proper parameters
          ./scripts/build.ps1 -UseVcpkg
          
          # Verify build artifacts
          Write-Host "=== Verifying Build Artifacts ==="
          $buildDir = "build-${{ matrix.platform }}"
          $artifacts = Get-ChildItem -Path $buildDir -Recurse -Include "*.obj", "*.lib", "*.exe", "*.pdb" -ErrorAction SilentlyContinue
          Write-Host "Found $($artifacts.Count) build artifacts in $buildDir"
          
          if ($artifacts.Count -eq 0) {
            Write-Error "No build artifacts found - build may have failed"
            exit 1
          } else {
            Write-Host "✅ Build verification passed"
          }
